### ISSUE TITLE
Failing codesignatureverifier - developer ID changed

### ISSUE THREAD

**Issue by duel007** [autopkg/jbaker10-recipes#8]
Noticed this:
`CodeSignatureVerifier: Expected: Developer ID Installer: ESET, spol. s r.o. -> Developer ID Certification Authority -> Apple Root CA`

`CodeSignatureVerifier: Found:    Developer ID Installer: ESET, spol. s r.o. (P8DQRXPVLP) -> Developer ID Certification Authority -> Apple Root CA`

It appears ESET has changed their developer ID but I'm unsure how to verify this, wanted to report.

**Comment by jbaker10** [comment]
@duel007 Sorry for the delay, this should be fixed with https://github.com/autopkg/jbaker10-recipes/pull/9. Please test and let me know if you still have issues.

**Comment by duel007** [comment]
Working now, thanks @jbaker10!
